//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

package com.pactera.bg3cs.tencent_live_flutter;

import android.content.Context;
import android.app.Activity;


import io.flutter.plugin.common.BinaryMessenger;

import io.flutter.plugin.common.StandardMessageCodec;
import io.flutter.plugin.platform.PlatformView;
import io.flutter.plugin.platform.PlatformViewFactory;


@SuppressWarnings("ALL")
class TXCloudPullViewFactory extends PlatformViewFactory{

    TXCloudPullViewFactory(BinaryMessenger messenger, Activity activity) {
        super(StandardMessageCodec.INSTANCE);
        this.messenger = messenger;
        this.activity = activity;
    }

    private BinaryMessenger messenger;
    private Activity activity;

    @Override
    public PlatformView create(Context context, int id, Object o) {
        return new FlutterTXCloudPullView(messenger, activity, id);
    }
}
